Change the default value of public_ip_dns
Using Terraform 0.12.x, if the current default value "" is used for `public_ip_dns` an error will occur:

```
Error: domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter and end only with a number or letter
```

so I propose changing the default value to `[null]` which will ensure that `domain_name_label` remains unset. I think this also addresses https://github.com/Azure/terraform-azurerm-compute/issues/13.

Thank you!