Update the default value for `public_ip_dns`
If the current default value is used in Terraform 0.12.x an error will occur:

```
Error: domain_name_label must contain only lowercase alphanumeric characters, numbers and hyphens. It must start with a letter and end only with a number or letter
```

so I propose simply adding some meaningless text for the default value. I think this also addresses https://github.com/Azure/terraform-azurerm-compute/issues/13.

Thank you!